### ISSUE TITLE
please provide an example of the same logic running on both longpoll and webhook

### ISSUE THREAD

**Issue by wchristian** [polettix/Bot-ChatBots-Telegram#4]
There are significant differences between those and the interplay between all the different parts is unclear. As such an example where the logic is contained in one module and is being consumed by different implementations for the bot engine types would be useful

To start with examples on unclear things and differences:

https://github.com/polettix/Bot-ChatBots-Telegram/blob/master/lib/Bot/ChatBots/Telegram/WebHook.pod
`   $record->{response} = 'your thoughs are important for us!';`

https://github.com/polettix/Bot-ChatBots-Telegram/blob/master/lib/Bot/ChatBots/Telegram/LongPoll.pod
`   $record->{send_response} = 'Hello, world!';`

Next one is the simple issue of how to have the bots do timed things on its own, not in response to anything. There are zero examples of this. I've worked out how to use `Mojo::IOLoop->timer` for longpoll to set things up before actually starting the bot, but i haven't even tried to apply the same to Webhook.

Then there's Telegram::Sender, which LongPoll mentions it uses, but doesn't mention that it also creates itself. Usage of that should be in synopsis. And Webhook doesn't seem to use sender at all? What is supposed to be the common shared api to send messages not in response to an incoming message?

Lastly, and this is a small aside: The module seems to assume that the user already knows how telegram bots work, which is a bit of a chicken/egg problem, since learning how to make a telegram bot will require looking at code that runs one and the examples provided are extremely simple and don't explicitly mention such facts as "bot is always online in telegram and your code is only a service that the telegram servers talk to", "can't make information requests about, e.g. what channels a bot is in", "bot needs to store all data it receives on its own as it can't query the telegram state". This should be mentioned as this thing is very different from an IRC bot, which is where most of the perl community will be coming from.

**Comment by polettix** [comment]
Thanks for the feedback!

- [x] add examples for generic usage and moving between longpoll/webhook
- [x] figure out examples for timed things in a bot
- [x] add more on `::Sender`
- [x] add a Tutorial guide providing background about Telegram and its architecture for bots
- [x] fix documentation error (see below)

Re "`send_response` vs `response`": it's a documentation error, the right one is `send_response`. As this is actually common across the two bot flavors, I'll probably note this in the reference documentation and explain it in the tutorial.

**Comment by polettix** [comment]
There were a few changes as a consequence of this feedback, so thanks again. A new trial release is on its way to CPAN, I'll freeze it as soon as CPAN Testers give me the go.

In the meantime, you might want to take a look at [the tutorial guide](https://github.com/polettix/Bot-ChatBots-Telegram/blob/master/lib/Bot/ChatBots/Telegram/Guide/Tutorial.pod). It does not probably work 100% with previous versions of the module, but mostly because of lack of the `->sender` method in web hooks; as hinted in the tutorial, though, this is easily addressed by creating a new sender instance. Feedback on this document is very welcome!

If you think that there are parts of your issue that haven't been addressed yet feel free to reopen this issue, of file another one. Thanks!

**Comment by wchristian** [comment]
Won't have time to do a deep read for a few days, but skimming the tutorial guide it looks perfect! :D

Thank you so much, and i will absolutely provide you with feedback. :)
